name: Submit iOS app

on:
  push:
    branches: ['main']

jobs:
  submit_ios:
    name: Submit iOS
    type: submit
    params:
      platform: ios
      # App configured with:
      # - Name: "Play in the Sandbox Looking at Flowers"
      # - Description: "playinginthesandbox"
      # - Bundle ID: "com.djscottyb.playsandbox" (explicit)
      # - App ID Prefix: "3X872JR6P3" (Team ID)
      # The following parameters are configured in eas.json under submit.production.ios
      # - appleId: "beilsco@gmail.com"
      # - ascAppId: "6477183822"
      # - appleTeamId: "3X872JR6P3"